CREATE TABLE `satellite_physical_characteristic_data`
(
  `Satellite`                      varchar(20) NOT NULL,
  `Radius`                         varchar(20) DEFAULT NULL,
  `RadiusUnit`                     varchar(5) DEFAULT NULL,
  `AxialTilt`                      varchar(20) DEFAULT NULL,
  `AxialTiltUnit`                  varchar(5) DEFAULT NULL,
  `MeanRadiance`                   varchar(20) DEFAULT NULL,
  `MeanRadianceUnit`               varchar(5) DEFAULT NULL,
  `SurfaceArea`                    varchar(20) DEFAULT NULL,
  `SurfaceAreaUnit`                varchar(5) DEFAULT NULL,
  `Volume`                         varchar(20) DEFAULT NULL,
  `VolumeUnit`                     varchar(5) DEFAULT NULL,
  `Mass`                           varchar(20) DEFAULT NULL,
  `MassUnit`                       varchar(5) DEFAULT NULL,
  `MeanDensity`                    varchar(20) DEFAULT NULL,
  `MeanDensityUnit`                varchar(5) DEFAULT NULL,
  `SurfaceGravity`                 varchar(20) DEFAULT NULL,
  `SurfaceGravityUnit`             varchar(5) DEFAULT NULL,
  `MomentOfInertiaFactor`          varchar(20) DEFAULT NULL,
  `MomentOfInertiaFactorUnit`      varchar(5) DEFAULT NULL,
  `EscapeVelocity`                 varchar(20) DEFAULT NULL,
  `EscapeVelocityUnit`             varchar(5) DEFAULT NULL,
  `SynodicRotationPeriod`          varchar(20) DEFAULT NULL,
  `SynodicRotationPeriodUnit`      varchar(5) DEFAULT NULL,
  `EquatorialRotationVelocity`     varchar(20) DEFAULT NULL,
  `EquatorialRotationVelocityUnit` varchar(5) DEFAULT NULL,
  `Albedo1`                        varchar(20) DEFAULT NULL,
  `Albedo1Unit`                    varchar(5) DEFAULT NULL,
  `Albedo2`                        varchar(20) DEFAULT NULL,
  `Albedo2Unit`                    varchar(5) DEFAULT NULL,
  `SurfaceMinimumTemperature`      varchar(20) DEFAULT NULL,
  `SurfaceMaximumTemperature`      varchar(20) DEFAULT NULL,
  `SurfaceMeanTemperature`         varchar(20) DEFAULT NULL,
  `TemperatureUnit`                varchar(5) DEFAULT NULL,
  `ApparentMagnitude`              varchar(20) DEFAULT NULL,
  `ApparentMagnitudeUnit`          varchar(5) DEFAULT NULL,
  `CreatedDateTime`                varchar(20) DEFAULT NULL,
  `LastModifiedDateTime`           varchar(20) DEFAULT NULL,
    PRIMARY KEY (`CodeName`),
    CONSTRAINT `SatellitePhysicalCharacteristicData_fk` FOREIGN KEY (`Satellite`) REFERENCES `satellite_general_data` (`Satellite`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
